# NumPy

### 1.1 NumPy 특징

- 과학 계산을 위한 라이브러리
- 행렬/배열 처리 및 연산
- 난수 생성 (Random Number)

### 1.2 배열의 생성

#### 1. 리스트에서 행렬/배열 생성

In [34]:
import numpy as np # numpy 패키지 로드하여 np로 사용
a = [[1,2,3], [4,5,6]] # 리스트에서 행렬생성
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]]


In [35]:
print(b.ndim) # 배열의 열수(차원)

2


In [36]:
print(b.shape) # 배열의 차원 2 x 3의 NumPy 2차원 배열

(2, 3)


In [37]:
print(b[0,0]) # 배열의 원소 접근

1


#### 2. 특수한 배열의 생성

In [38]:
print(np.arange(10)) # 1씩 증가하는 1차원 배열(시작이 0부터)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
print(np.arange(5,10)) # 1씩 증가하는 1차원 배열(시작이 5부터)

[5 6 7 8 9]


In [40]:
print(np.zeros((2,2))) # 2 x 2 영 배열 생성

[[0. 0.]
 [0. 0.]]


In [41]:
print(np.ones((2,3))) # 2 x 3 유닛행렬

[[1. 1. 1.]
 [1. 1. 1.]]


In [42]:
print(np.full((2,3), 5)) # 모든 원소가 5인 2 x 3 행렬

[[5 5 5]
 [5 5 5]]


In [43]:
print(np.eye(3)) # 단위 행렬 (주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 3. 배열의 차원 변환

In [44]:
a = np.arange(20) # 1씩 증가하는..
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [45]:
# b = np.reshape(a,(4,5)) # 같음
b = a.reshape((4,5))
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### 1.3 Numpy 슬라이싱/ 인덱싱

In [46]:
import numpy as np
lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
arr = np.array(lst) # 배열 생성
# a = arr[0:2, 0:2] # 2 x 2 배열로 슬라이싱
# print(a)
a = arr[0:3, 0:2] # 3 x 2 배열로 슬라이싱
print(a)

[[1 2]
 [4 5]
 [7 8]]


In [47]:
a = arr[1:, 1:]
print(a)

[[5 6]
 [8 9]]


In [48]:
a = arr[:2, 1:]
print(a)

[[2 3]
 [5 6]]


In [49]:
# a = arr[2]
# a = arr[2, :]
a = arr[2:, :] # 1 x 3 행렬
print(a)

[[7 8 9]]


In [50]:
a = arr[:, :2]
print(a)

[[1 2]
 [4 5]
 [7 8]]


In [51]:
# a = arr[1:, :2]
a = arr[1:2, :2] # 1 x 2 행렬
print(a)

[[4 5]]


### 1.4 Numpy 연산

- 배열간 연산 가능
- +, -, *, / 등의 연산자 사용가능
- add(), substract(), multiply(), divide()

In [52]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

# 각 요소 더하기
c = a + b

# c = np.add(a,b)
print(c) # [5, 7, 9]

# 각 요소 곱하기
# c = a * b

c = np.multiply(a,b)
print(c) #[4, 10, 18]

# 각 요소 나누기
# c = a / b

c = np.divide(a,b)
print(c) #[0.25, 0.4, 0.5]

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


- dot() 함수: 행렬의 곱

In [55]:
import numpy as np

arr1 = [[1,2], [3,4]]
arr2 = [[5,6], [7,8]]
a = np.array(arr1)
b = np.array(arr2)

c = np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


- 모든 원소의 합: sum()
- 모든 원소의 곱: prod()

In [57]:
import numpy as np

a = np.array([[-1,2,3],[3,4,8]])
s = np.sum(a)
print('sum =',a.sum())

sum = 19


In [58]:
# 행렬/열별 연산 (axis=0/1)
print('sum by row = ', a.sum(axis = 0))

sum by row =  [ 2  6 11]
